### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by robertjriga** [Manisso/fsociety#37] opened 2018-02-20 19:18 UTC
Hey everyone!
This tool is amazing I can't even get how you created it, I am just amazed by your skills.
Installing tool on android terminal I get this issue,how can I fix it?
File"/data/data/com.termux/files/usr/usr/share/doc/fsociety/fsociety.py, line 1136 except( ), message 
                                                                                                                                                 ^
SyntaxError: invalid syntax

Can you help me to resolve it?

**Comment by robertjriga** [comment] 2018-02-20 20:27
Fixed)
pip2 install requests
chmod +x fsociety.py
python2 fsociety.py

**Comment by thehappydinoa** [comment] 2018-02-21 15:01
Duplicate of #36

**Closed** 2018-02-21 15:02 UTC
Labels: duplicate

**Comment by eplusp** [comment] 2018-04-14 17:44
Just do this:
$Cd /data/data/com.termux/files/usr/bin
$ fsociety

And then
Just find python command and replace python2
Save it
Done !

**Comment by eplusp** [comment] 2018-04-14 17:47
Just do this:
$Cd /data/data/com.termux/files/usr/bin
$ nano fsociety

And then
Just find 'python' text and replace 'python2'
Save it
Done !
