### ISSUE TITLE
Termux problem

### ISSUE THREAD

**Issue by mortalwolf** [Manisso/fsociety#31] opened 2018-02-05 18:13 UTC
Hi i have a problem for install this package

https://drive.google.com/open?id=1T7tv2GdYgslekMKu1yoQKW5BHlaTZ29Y

**Comment by mortalwolf** [comment] 2018-02-05 18:18
https://imgur.com/a/Oktaa

**Comment by thehappydinoa** [comment] 2018-02-05 19:33
Hey, I'll look into this

**Comment by thehappydinoa** [comment] 2018-02-06 13:19
Hey this is a duplicate of [#28](https://github.com/Manisso/fsociety/issues/28)

**Comment by mortalwolf** [comment] 2018-02-08 13:06
How can i solve it

**Comment by thehappydinoa** [comment] 2018-02-08 13:09
So I am actually working on rewriting lots so just give me sometime. I have been really busy with school recently.

**Comment by thehappydinoa** [comment] 2018-02-08 13:24
I get the same error while running Python 3.6.1 Python 3 is not supported.
```python
Python 3.6.1 (default, Dec 2015, 13:05:11)
[GCC 4.8.2] on linux
   
Traceback (most recent call last):
  File "python", line 705
    print """
      Reaver has been designed to be a robust and practical attack against Wi-Fi Protected Setup
      WPS registrar PINs in order to recover WPA/WPA2 passphrases. It has been tested against a
      wide variety of access points and WPS implementations
      1 to accept / 0 to decline
        """
             
                                                                                                
                                                                                               
                                                           
                                
          ^
SyntaxError: Missing parentheses in call to 'print'
```

**Closed by thehappydinoa** 2018-02-08 13:24 UTC
Labels: bug
